"""Every filesystem path remanga touches, in one package: roots, tools,
per-project layout, project metadata, shared assets. Never build a path inline
elsewhere - add it here."""

from __future__ import annotations

from .global_assets import ensure_hf_token_file, get_hf_token_path
from .metadata import (
    chapter_identity_fields,
    get_manifest_path,
    get_project_metadata_path,
    list_projects,
    load_project_metadata,
    read_manifest,
    read_remote_chapter_cache,
    save_project_metadata,
    update_manifest_chapter,
    write_remote_chapter_cache,
)
from .projects import (
    GENERATED_KINDS,
    get_audio_dir,
    get_audio_timing_path,
    get_chapter_dir,
    get_crops_path,
    get_final_video_path,
    get_generated_dir,
    get_log_path,
    get_master_audio_path,
    get_modified_audio_dir,
    get_narration_path,
    get_pages_dir,
    get_panels_dir,
    get_pdf_dir,
    get_project_dir,
    get_projects_dir,
    get_video_concat_path,
    get_video_dir,
    get_video_frames_dir,
    get_video_picture_path,
    get_video_work_dir,
)
from .review import get_narration_review_history_dir, get_narration_review_path
from .roots import BIN_DIR, CONFIG_EXAMPLE_PATH, CONFIG_PATH, GLOBAL_DIR, PROMPTS_DIR, REPO_ROOT, TOOLS_DIR, UV_BIN
from .tools import get_scripts_dir
from .webui_static import MARKER_STATIC_DIR, REVIEWER_STATIC_DIR, SHARED_STATIC_DIR, WRITER_STATIC_DIR

__all__ = [
    "BIN_DIR",
    "CONFIG_EXAMPLE_PATH",
    "CONFIG_PATH",
    "GENERATED_KINDS",
    "GLOBAL_DIR",
    "MARKER_STATIC_DIR",
    "PROMPTS_DIR",
    "REPO_ROOT",
    "REVIEWER_STATIC_DIR",
    "SHARED_STATIC_DIR",
    "TOOLS_DIR",
    "UV_BIN",
    "WRITER_STATIC_DIR",
    "chapter_identity_fields",
    "ensure_hf_token_file",
    "get_audio_dir",
    "get_audio_timing_path",
    "get_chapter_dir",
    "get_crops_path",
    "get_final_video_path",
    "get_generated_dir",
    "get_hf_token_path",
    "get_log_path",
    "get_manifest_path",
    "get_master_audio_path",
    "get_modified_audio_dir",
    "get_narration_path",
    "get_narration_review_history_dir",
    "get_narration_review_path",
    "get_pages_dir",
    "get_panels_dir",
    "get_pdf_dir",
    "get_project_dir",
    "get_project_metadata_path",
    "get_projects_dir",
    "get_scripts_dir",
    "get_video_concat_path",
    "get_video_dir",
    "get_video_frames_dir",
    "get_video_picture_path",
    "get_video_work_dir",
    "list_projects",
    "load_project_metadata",
    "read_manifest",
    "read_remote_chapter_cache",
    "save_project_metadata",
    "update_manifest_chapter",
    "write_remote_chapter_cache",
]
