"""Shared JSON read/write helpers so every module stops re-implementing open()+json.load/dump."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any


def read_json(path: Path | str) -> Any:
    """Reads and parses a JSON file. Raises FileNotFoundError/JSONDecodeError if missing or invalid."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def read_json_or(path: Path | str, default: Any = None) -> Any:
    """Reads JSON, returning `default` if the file is missing, empty, or unparsable."""
    try:
        return read_json(path)
    except Exception:
        return default


def write_json(path: Path | str, data: Any, indent: int = 2) -> None:
    """Serializes `data` as indented JSON, creating parent directories as needed.
    Writes to a temp file in the same directory, then atomically renames it over
    the target (os.replace) - a write-in-place here would leave `path` holding a
    truncated/corrupt file if the process is killed mid-write, which matters more
    now that narration.json gets autosaved on close to every keystroke pause in
    the Narration Writer (see webui/writer_routes.py) rather than only on an
    explicit Save."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=indent)
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


# Minimum byte size a real, LLM-pasted JSON file is expected to clear. Blank
# placeholders (crops.json/narration.json) are written as an empty string by the
# wizard, so any positive threshold works; this just guards against a stray
# whitespace-only save being mistaken for real content.
PLACEHOLDER_MAX_BYTES = 10


def has_real_json_content(path: Path | str) -> bool:
    """True if `path` exists and holds more than a blank placeholder - the shared
    check used by the wizard, CLI, and status panel to decide whether crops.json /
    narration.json still need to be generated by an LLM."""
    p = Path(path)
    return p.exists() and p.stat().st_size > PLACEHOLDER_MAX_BYTES
